modLoader="javafml"
loaderVersion="[1,)"
license="GPL-3.0 License"

[[mods]]
modId="novanillaprogression"
version="1.0"
displayName="No Tree Punching Remastered"
authors="WoodIsDaniel"
description='''
No Tree Punching for 1.21.1.
Batteries not included.
'''
logoFile="icon.png"


# Dependency for Minecraft
[[dependencies.novanillaprogression]]
modId="minecraft"
type="required"
versionRange="[1.21, 1.21.1)"
ordering="AFTER"
side="BOTH"

# Dependency for Neoforge
[[dependencies.novanillaprogression]]
modId="neoforge"
type="required"
versionRange="[21.0.167,)"
ordering="AFTER"
side="BOTH"